[package]
name = "akton-arn"
version = "0.1.0"
edition = "2021"
authors = ["Govcraft <contact@govcraft.ai>"]
description = "A Rust library for handling Akton Resource Names (ARNs), providing tools for generating, parsing, and managing ARNs within Akton-based cloud-native solutions."
repository = "https://github.com/govcraft/akton-arn"
documentation = "https://docs.rs/akton-arn"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["arn", "resource-management", "cloud", "actor"]
categories = ["api-bindings", "cryptography", "data-structures", "network-programming", "authentication"]
homepage = "https://govcraft.com/akton-arn"

[dependencies]

